// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR_6knnYftL1lfJ6GCahGXLhC5TR3rAQM',
    appId: '1:1042521521698:web:d1201901959cbc8903547b',
    messagingSenderId: '1042521521698',
    projectId: 'linereview-project',
    authDomain: 'linereview-project.firebaseapp.com',
    storageBucket: 'linereview-project.appspot.com',
    measurementId: 'G-D6PG5VG44Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnpA9TQU6ix-HHyRC2ZHX0MDipMclfDhQ',
    appId: '1:1042521521698:android:80167138ae80e2b003547b',
    messagingSenderId: '1042521521698',
    projectId: 'linereview-project',
    storageBucket: 'linereview-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsVFWtOi0KvE5OAyy2Ceooyi8TfwQsflU',
    appId: '1:1042521521698:ios:793663e4be63b70303547b',
    messagingSenderId: '1042521521698',
    projectId: 'linereview-project',
    storageBucket: 'linereview-project.appspot.com',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsVFWtOi0KvE5OAyy2Ceooyi8TfwQsflU',
    appId: '1:1042521521698:ios:793663e4be63b70303547b',
    messagingSenderId: '1042521521698',
    projectId: 'linereview-project',
    storageBucket: 'linereview-project.appspot.com',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR_6knnYftL1lfJ6GCahGXLhC5TR3rAQM',
    appId: '1:1042521521698:web:3094d74967ba580e03547b',
    messagingSenderId: '1042521521698',
    projectId: 'linereview-project',
    authDomain: 'linereview-project.firebaseapp.com',
    storageBucket: 'linereview-project.appspot.com',
    measurementId: 'G-RLMGVCGGV4',
  );
}
